from typing import ClassVar, Tuple
from array import array
from MLTooling.core.dtypes import Dtypes
from MLTooling.core.shape import Shape

class Matrix:
    _type: int
    _c_mat_f: ClassVar
    _cmat_d: ClassVar

    def __init__(self, rows: int, cols: int, dtype: Dtypes = Dtypes.FLOAT32): ...

    @classmethod
    def from_buffer(cls, rows: int, cols: int, data:array) -> "Matrix": ...

    @classmethod 
    def _from_ptr(cls, ptr: int) -> "Matrix": ...

    def __dealloc__(self) -> None: ...

    def __getitem__(self, key: Tuple[int, int]) -> float: ...
    def __setitem__(self, key: Tuple[int, int], value: float) -> None: ...
    def __add__(self, other: "Matrix") -> "Matrix": ...
    def __iadd__(self, other: "Matrix") -> "Matrix": ...
    def __matmul__(self, other: Matrix) -> "Matrix": ...
    def shape(self) -> "Shape": ...
    def clone(self) -> "Matrix": ...
    def copy(self) -> "Matrix": ...
    def submatrix(self, start: "Shape", count: "Shape") -> "Matrix": ...
